services:
  - type: web
    name: moesconverter-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: "*"
      - key: MAX_FILE_SIZE
        value: 1073741824
      - key: FILE_TTL_MS
        value: 900000
      - key: ADMIN_EMAIL
        value: gmateosoficial@gmail.com
      - key: ADMIN_USERNAME
        value: momo
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    autoDeploy: true
